
    document.addEventListener('DOMContentLoaded',()=>{const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],root=document.documentElement,loader=$('#loader'),fill=$('#loaderFill'),pct=$('#loaderPct'),nav=$('#mainNav'),ticks=$('#signalTicks'),sections=$$('[data-signal]');
      const saved=localStorage.getItem('portfolio-theme');if(saved==='light')root.classList.add('light');const theme=$('#themeToggleBtn');const sync=()=>theme.innerHTML=root.classList.contains('light')?'<i class="fas fa-sun"></i>':'<i class="fas fa-moon"></i>';sync();theme.addEventListener('click',()=>{root.classList.toggle('light');localStorage.setItem('portfolio-theme',root.classList.contains('light')?'light':'dark');sync()});
      const words=['Android products','Clear product thinking','Native performance','Useful collaboration','Measured growth'];$('#tickerTrack').innerHTML=[...words,...words].map(w=>`<span><i class="fas fa-circle"></i>${w}</span>`).join('');
      ticks.innerHTML=sections.map((s,i)=>`<button class="signal-tick" style="top:${sections.length>1?i/(sections.length-1)*100:0}%" data-target="${s.id}" aria-label="Go to ${s.dataset.signal}"></button>`).join('');$$('.signal-tick').forEach(t=>t.addEventListener('click',()=>$('#'+t.dataset.target)?.scrollIntoView({behavior:'smooth'})));
      const update=()=>{const range=Math.max(document.documentElement.scrollHeight-innerHeight,1),p=Math.min(scrollY/range,1);$('#signalFill').style.height=`${p*100}%`;$('#topProgress').style.transform=`scaleX(${p})`;nav.classList.toggle('scrolled',scrollY>20);let active=sections[0];sections.forEach(s=>{if(s.getBoundingClientRect().top<innerHeight*.42)active=s});$$('.signal-tick').forEach(t=>t.classList.toggle('active',t.dataset.target===active?.id));$$('.reveal').forEach(e=>{if(e.getBoundingClientRect().top<innerHeight*.88)e.classList.add('visible')})};update();addEventListener('scroll',update,{passive:true});addEventListener('resize',update);
      let n=0;const timer=setInterval(()=>{n+=10;fill.style.width=n+'%';pct.textContent=n+'%';if(n>=100){clearInterval(timer);setTimeout(()=>loader.classList.add('done'),220)}},55);
      if(new URLSearchParams(location.search).get('status')==='success'){$('#formBody').style.display='none';$('#successMsg').style.display='flex'}const form=$('#contactForm');form?.addEventListener('submit',()=>{$('#btnText').textContent='Transmitting...';$('#submitBtn').style.pointerEvents='none'});
      const dot=$('#cursorDot'),ring=$('#cursorRing'),spot=$('#spotlight');if(matchMedia('(hover:hover)').matches){document.body.classList.add('has-cursor');addEventListener('mousemove',e=>{dot.style.transform=`translate(${e.clientX}px,${e.clientY}px)`;ring.style.transform=`translate(${e.clientX}px,${e.clientY}px)`;root.style.setProperty('--mx',e.clientX+'px');root.style.setProperty('--my',e.clientY+'px');ring.classList.add('show');spot.classList.add('active')});$$('a,button,input,textarea').forEach(el=>{el.addEventListener('mouseenter',()=>ring.classList.add('expand'));el.addEventListener('mouseleave',()=>ring.classList.remove('expand'))})}
    });
  